const Colors = {
    PRIMARY_COLOR: '#33B9D4',
    TEXT_COLOR: '#4B4B4B',
    FOOTER_BACKGROUND_COLOR: '#EAEAEA',
    ERROR_COLOR: '#B64242',
    RADIO_TEXT: '#727272',
    BUTTON_VERSUS_ICON: '#C33232',
    BUTTON_VERSUS_BACKGROUND: '#E9989E',
    LINE_COLOR: '#e3e3e3',
    TEXT_INPUT_BACKGROUND: '#f5f5f5'
}

module.exports = Colors;
